#!/bin/sh

sudo apt-get install default-jdk
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.zip
sudo apt-get install unzip

mkdir env
unzip elasticsearch-1.2.1 -d env/
rm elasticsearch-1.2.1.zip

cd env/elasticsearch-1.2.1/
bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.1.1
bin/plugin -install mobz/elasticsearch-head
bin/plugin -install elasticsearch/elasticsearch-lang-python/2.0.0


#bin/elasticsearch
